from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .license_inventory import licenses_from_sbom
from .models import ScanResult
from .utils import count_trivy_findings, ensure_dir, load_json, write_json


DOCUMENT_COVERAGE: list[dict[str, str]] = [
    {
        "case": "Trivy install / version check",
        "document": "trivy.exe --version, document sample uses Trivy 0.65.0",
        "implementation": "Tool requires trivy in PATH and fails clearly when it is missing.",
        "status": "PRECONDITION",
        "difference": "The scanner does not install Trivy automatically.",
    },
    {
        "case": "Dependency vulnerability scan",
        "document": "trivy sbom sbom.json --scanners vuln --format template ... -o report-vuln.html",
        "implementation": "Runs trivy sbom --scanners vuln --format json, then builds report-vuln.html from vuln.json.",
        "status": "COVERED",
        "difference": "HTML is generated by this tool instead of Trivy html.tpl.",
    },
    {
        "case": "Gradle license scan",
        "document": "Apply org.cyclonedx.bom 2.3.1, run gradlew cyclonedxBom, normalize, scan license JSON/TXT.",
        "implementation": "Runs gradlew/gradle cyclonedxBom; if plugin is missing, uses a temporary init script with org.cyclonedx.bom 2.3.1, then normalizes and scans license.",
        "status": "COVERED",
        "difference": "Does not edit build.gradle/build.gradle.kts; the init script is created in scan output.",
    },
    {
        "case": "Maven license scan",
        "document": "mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom, normalize bom.json, scan license JSON/TXT.",
        "implementation": "Prefers mvnw/mvnw.cmd, then mvn; runs makeAggregateBom to create a fresh SBOM in the run folder, then normalizes and scans license.",
        "status": "COVERED",
        "difference": "Output is stored under scan-results for this run instead of target/bom.json.",
    },
    {
        "case": "Node.js npm/package-lock license scan",
        "document": "Create third-party, run cyclonedx npm command to sbom.json, normalize, scan license JSON/TXT.",
        "implementation": "Runs npx --yes @cyclonedx/cyclonedx-npm --ignore-npm-errors; with package-lock/npm-shrinkwrap it uses --package-lock-only.",
        "status": "COVERED",
        "difference": "Writes SBOM to scan-results, not third-party, to avoid stale SBOM on re-scan.",
    },
    {
        "case": ".NET license scan",
        "document": "Install CycloneDX dotnet tool, run dotnet-CycloneDX <project> -j, normalize bom.json, scan license JSON/TXT.",
        "implementation": "Installs CycloneDX when missing and dotnet exists; runs dotnet-CycloneDX against the first .sln/.csproj found, then normalizes and scans license.",
        "status": "COVERED",
        "difference": "Output is copied into scan-results for the current run.",
    },
    {
        "case": "SBOM license normalization",
        "document": "Run convert-sbom.py to produce *-fix.json before Trivy license scan.",
        "implementation": "Runs internal license_normalizer to produce SBOM.cdx-fix.json and license-normalize.log.",
        "status": "COVERED",
        "difference": "Implemented inside Python package instead of external convert-sbom.py.",
    },
    {
        "case": "License JSON and TXT outputs",
        "document": "trivy sbom --scanners license -o c4t.txt and -f json -o c4t.json.",
        "implementation": "Runs one combined Trivy scan, then derives license.txt and license.json from report.json for every successful service scan.",
        "status": "COVERED",
        "difference": "File names are standardized per service output folder; fewer Trivy commands are used for speed.",
    },
    {
        "case": "Missing license rows from Trivy",
        "document": "Review license report for all SBOM packages.",
        "implementation": "Backfills report.json/license.json from SBOM.cdx-fix.json when Trivy omits package license rows.",
        "status": "COVERED_PLUS",
        "difference": "Adds LicenseRef-No-Declared-License for components that declare no license.",
    },
    {
        "case": "Script CI/CD/Jenkins license scan and email",
        "document": "Scripts scan SBOMs under third-party/sbom-reports and send result via email.",
        "implementation": "Not implemented in this local runner.",
        "status": "EXCLUDED_BY_SCOPE",
        "difference": "Excluded by user request; local folder scan remains the target.",
    },
    {
        "case": "SonarQ/SonarQube",
        "document": "Document includes SonarQ-related flow.",
        "implementation": "Not implemented.",
        "status": "EXCLUDED_BY_SCOPE",
        "difference": "Excluded by user request.",
    },
]


def _as_text(value: Any) -> str:
    if value is None:
        return "-"
    text = str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _command_text(command: list[str]) -> str:
    return " ".join(str(part) for part in command)


def _safe_json(path: Path | None) -> dict[str, Any]:
    if not path or not path.is_file():
        return {}
    try:
        data = load_json(path)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _license_name(entry: dict[str, Any]) -> str:
    if entry.get("expression"):
        return str(entry.get("expression") or "").strip()
    license_obj = entry.get("license")
    if not isinstance(license_obj, dict):
        return ""
    return str(
        license_obj.get("id")
        or license_obj.get("name")
        or license_obj.get("url")
        or ""
    ).strip()


def _sbom_stats(path: Path | None) -> dict[str, Any]:
    data = _safe_json(path)
    if not data:
        return {"exists": bool(path and path.is_file())}

    components = [item for item in data.get("components") or [] if isinstance(item, dict)]
    components_with_license = 0
    components_without_license = 0
    license_entries = 0
    unique_licenses: set[str] = set()
    for component in components:
        licenses = component.get("licenses") or []
        names = [
            _license_name(entry)
            for entry in licenses
            if isinstance(entry, dict)
        ]
        names = [name for name in names if name]
        if names:
            components_with_license += 1
            license_entries += len(names)
            unique_licenses.update(names)
        else:
            components_without_license += 1

    return {
        "exists": True,
        "bom_format": data.get("bomFormat"),
        "spec_version": data.get("specVersion"),
        "components_total": len(components),
        "components_with_license": components_with_license,
        "components_without_license": components_without_license,
        "license_entries": license_entries,
        "unique_licenses": len(unique_licenses),
    }


def _trivy_stats(path: Path | None) -> dict[str, Any]:
    if not path or not path.is_file():
        return {"exists": False}
    try:
        vuln_count, license_count = count_trivy_findings(path)
    except (OSError, ValueError):
        return {"exists": True, "readable": False}
    return {
        "exists": True,
        "readable": True,
        "vulnerabilities": vuln_count,
        "licenses": license_count,
    }


def _license_inventory_count(path: Path | None) -> int | None:
    if not path or not path.is_file():
        return None
    try:
        return len(licenses_from_sbom(path))
    except (OSError, ValueError):
        return None


def _tail_lines(path: Path, limit: int = 40) -> list[str]:
    if not path.is_file():
        return []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return []
    return lines[-limit:]


def _top_level_lock_files(project_path: Path) -> list[str]:
    names = (
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "bun.lock",
        "bun.lockb",
        "pom.xml",
        "build.gradle",
        "build.gradle.kts",
        "settings.gradle",
        "settings.gradle.kts",
        "pubspec.lock",
        "go.sum",
        "composer.lock",
        "Gemfile.lock",
        "poetry.lock",
        "Pipfile.lock",
    )
    return [name for name in names if (project_path / name).is_file()]


def _service_debug(result: ScanResult) -> dict[str, Any]:
    scan_log = result.output_dir / "scan.log"
    normalize_log = result.output_dir / "license-normalize.log"
    return {
        "name": result.name,
        "status": result.status,
        "kind": result.project_kind,
        "source_path": str(result.project_path),
        "output_dir": str(result.output_dir),
        "markers": result.project_markers,
        "top_level_lock_or_build_files": _top_level_lock_files(result.project_path),
        "sbom_status": result.sbom_status,
        "paths": {
            "sbom": str(result.sbom_path) if result.sbom_path else None,
            "fixed_sbom": str(result.fixed_sbom_path) if result.fixed_sbom_path else None,
            "report_json": str(result.report_json) if result.report_json else None,
            "report_html": str(result.report_html) if result.report_html else None,
            "license_json": str(result.license_json) if result.license_json else None,
            "license_txt": str(result.license_txt) if result.license_txt else None,
            "vuln_json": str(result.vuln_json) if result.vuln_json else None,
            "vuln_html": str(result.vuln_html) if result.vuln_html else None,
            "scan_log": str(scan_log),
            "license_normalize_log": str(normalize_log),
        },
        "counts": {
            "reported_vulnerabilities": result.vuln_count,
            "reported_licenses": result.license_count,
            "raw_sbom": _sbom_stats(result.sbom_path),
            "fixed_sbom": _sbom_stats(result.fixed_sbom_path),
            "report_json": _trivy_stats(result.report_json),
            "license_json": _trivy_stats(result.license_json),
            "vuln_json": _trivy_stats(result.vuln_json),
            "license_rows_from_fixed_sbom": _license_inventory_count(result.fixed_sbom_path),
        },
        "commands": [
            {
                "command": record.command,
                "command_text": _command_text(record.command),
                "cwd": record.cwd,
                "returncode": record.returncode,
                "duration_seconds": record.duration_seconds,
                "stdout_tail": record.stdout_tail,
                "stderr_tail": record.stderr_tail,
            }
            for record in result.commands
        ],
        "notes": result.notes,
        "errors": result.errors,
        "internal_debug": result.debug,
        "scan_log_tail": _tail_lines(scan_log),
        "license_normalize_log_tail": _tail_lines(normalize_log),
    }


def build_debug_data(
    root: Path,
    run_dir: Path,
    output_base: Path,
    results: list[ScanResult],
    merged_report: Path | None,
    dry_run: bool,
) -> dict[str, Any]:
    ok = sum(1 for result in results if result.status == "OK")
    failed = sum(1 for result in results if result.status == "FAIL")
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "root": str(root),
        "run_dir": str(run_dir),
        "output_base": str(output_base),
        "mode": "dry-run" if dry_run else "scan",
        "consolidated_report": str(merged_report) if merged_report else None,
        "summary": {
            "total_projects": len(results),
            "ok": ok,
            "failed": failed,
            "dry_run": dry_run,
            "unique_kinds": sorted({result.project_kind for result in results}),
        },
        "scope_notes": [
            "SonarQ/SonarQube is excluded by user request.",
            "CI/CD/Jenkins/email scripts are excluded by user request.",
            "SBOM is regenerated into scan-results on every run; existing SBOM files in source are not reused.",
        ],
        "document_coverage": DOCUMENT_COVERAGE,
        "services": [_service_debug(result) for result in results],
    }


def _markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_as_text(value) for value in row) + " |")
    return lines


def render_debug_markdown(data: dict[str, Any]) -> str:
    summary = data["summary"]
    lines: list[str] = [
        "# Auto Scan Debug Report",
        "",
        f"- Generated at: {data['generated_at']}",
        f"- Root: `{data['root']}`",
        f"- Run dir: `{data['run_dir']}`",
        f"- Mode: `{data['mode']}`",
        f"- Projects: {summary['total_projects']} (OK: {summary['ok']}, FAIL: {summary['failed']})",
        "",
        "## Scope",
        "",
    ]
    for note in data["scope_notes"]:
        lines.append(f"- {note}")

    lines.extend([
        "",
        "## Document Coverage",
        "",
    ])
    lines.extend(_markdown_table(
        ["Case", "Status", "Source-code behavior", "Difference"],
        [
            [
                item["case"],
                item["status"],
                item["implementation"],
                item["difference"],
            ]
            for item in data["document_coverage"]
        ],
    ))

    lines.extend([
        "",
        "## Services",
        "",
    ])
    lines.extend(_markdown_table(
        ["Service", "Kind", "Status", "SBOM", "Fixed components", "Version updates", "SBOM license rows", "Trivy licenses", "Markers"],
        [
            [
                service["name"],
                service["kind"],
                service["status"],
                service["sbom_status"],
                service["counts"]["fixed_sbom"].get("components_total", "-"),
                (service["internal_debug"].get("version_reconcile_stats") or {}).get("updated_components", "-"),
                service["counts"].get("license_rows_from_fixed_sbom", "-"),
                service["counts"]["report_json"].get("licenses", "-"),
                ", ".join(service["markers"]) or "-",
            ]
            for service in data["services"]
        ],
    ))

    for service in data["services"]:
        lines.extend([
            "",
            f"### {service['name']}",
            "",
            f"- Source: `{service['source_path']}`",
            f"- Output: `{service['output_dir']}`",
            f"- Kind/markers: `{service['kind']}` / `{', '.join(service['markers']) or '-'}`",
            f"- Top-level lock/build files: `{', '.join(service['top_level_lock_or_build_files']) or '-'}`",
            f"- SBOM status: `{service['sbom_status']}`",
            f"- Scan log: `{service['paths']['scan_log']}`",
            f"- License normalize log: `{service['paths']['license_normalize_log']}`",
        ])
        version_stats = service["internal_debug"].get("version_reconcile_stats") or {}
        if version_stats and (version_stats.get("candidate_packages") or version_stats.get("updated_components")):
            lines.append(
                "- Version reconcile: "
                f"`{version_stats.get('updated_components', 0)}` updated component(s), "
                f"`{version_stats.get('candidate_packages', 0)}` candidate package(s)"
            )
            for item in (version_stats.get("updates") or [])[:10]:
                lines.append(
                    f"  - `{item.get('package')}`: "
                    f"`{item.get('from')}` -> `{item.get('to')}` "
                    f"from `{item.get('source')}`"
                )
        failed_commands = [
            command for command in service["commands"]
            if command["returncode"] != 0
        ]
        successful_commands = [
            command for command in service["commands"]
            if command["returncode"] == 0
        ]
        if failed_commands and successful_commands:
            first_failed = failed_commands[0]
            first_success = successful_commands[0]
            lines.append(
                "- Retry/fallback note: "
                f"`{first_failed['command_text']}` exited `{first_failed['returncode']}`, "
                f"then `{first_success['command_text']}` succeeded"
            )
        if failed_commands:
            lines.extend(["", "Command failures:", ""])
            for command in failed_commands[:5]:
                lines.append(f"- `[exit {command['returncode']}]` `{command['command_text']}`")
                for line in (command.get("stderr_tail") or [])[-5:]:
                    lines.append(f"  - `{line}`")
        if service["errors"]:
            lines.append(f"- Errors: `{'; '.join(service['errors'])}`")

        lines.extend([
            "",
            "Commands:",
            "",
        ])
        if service["commands"]:
            for index, command in enumerate(service["commands"], start=1):
                lines.append(
                    f"{index}. `[exit {command['returncode']}]` "
                    f"`{command['command_text']}` "
                    f"({command['duration_seconds']}s)"
                )
        else:
            lines.append("- No external commands were run.")

    lines.extend([
        "",
        "## How To Debug Missing Packages",
        "",
        "1. If `fixed components` is lower than expected, inspect the SBOM generation command and `scan.log`.",
        "2. If `fixed components` is correct but `Trivy licenses` is lower, check the SBOM backfill section in `scan.log`.",
        "3. If a Node.js frontend is missing transitive packages, check lock files in the service row and commit the correct lock file.",
        "4. Use `--dry-run` to confirm every service folder is detected before running the full scan.",
        "",
    ])
    return "\n".join(lines)


def write_debug_reports(
    root: Path,
    run_dir: Path,
    output_base: Path,
    results: list[ScanResult],
    merged_report: Path | None,
    dry_run: bool,
) -> dict[str, Path]:
    ensure_dir(run_dir)
    ensure_dir(output_base)
    data = build_debug_data(root, run_dir, output_base, results, merged_report, dry_run)
    markdown = render_debug_markdown(data)

    run_json = run_dir / "debug-report.json"
    run_md = run_dir / "debug-report.md"
    stable_json = output_base / "debug-report.json"
    stable_md = output_base / "debug-report.md"

    write_json(run_json, data)
    write_json(stable_json, data)
    run_md.write_text(markdown, encoding="utf-8")
    stable_md.write_text(markdown, encoding="utf-8")

    return {
        "debug_report": run_md,
        "debug_report_json": run_json,
        "stable_debug_report": stable_md,
        "stable_debug_report_json": stable_json,
    }
